### ISSUE TITLE
Cache template to html file

### ISSUE THREAD

**Issue by kamov** [Xeoncross/PHP-Template#6]
hi,
is possible and where I can save to cache full html template?
Thanks

**Comment by xeoncross** [comment]
This process is so ridiculously fast there isn't much point caching templates unless you simply want to cache an expensive process inside the template.

Either way, you are free to cache the string output from Template and put inside a database, memcached, redis, or [just plan files](https://gist.github.com/johndyer/817809).

**Comment by kamov** [comment]
Thanks, I was able to make this.
